name: .NET Core

on:
  push:
    branches: [ err/migrate-netstandard ]
  pull_request:
    branches: [ err/migrate-netstandard ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Generate build number
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Set Variables and build
      run: |
        echo "DAY=$(date -d "$D" '+%-d')" >> $DAY
        echo "MONTH=$(date -d "$D" '+%-m')" >> $MONTH
        echo "YEAR=$(date -d "$D" '+%y')" >> $YEAR
        echo "VERSION=1.$YEAR.$MONTH.$DAY$BUILD_NUMBER" >> $VERSION                
        dotnet build ./Logging/QuantConnect.Logging.csproj -p:Version=$VERSION --configuration Release
        dotnet build ./Configuration/QuantConnect.Configuration.csproj -p:Version=$VERSION --configuration Release
        dotnet build ./Common/QuantConnect.csproj -p:Version=$VERSION --configuration Release
        dotnet build ./Indicators/QuantConnect.Indicators.csproj -p:Version=$VERSION --configuration Release
        dotnet nuget push ./Logging/bin/Release/QuantConnect.Logging.$VERSION.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_URL }}
        dotnet nuget push ./Configuration/bin/Release/QuantConnect.Configuration.$VERSION.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_URL }}
        dotnet nuget push ./Common/bin/Release/QuantConnect.$VERSION.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_URL }}
        dotnet nuget push ./Indicators/bin/Release/QuantConnect.Indicators.$VERSION.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_URL }}

#    - name: Install dependencies
#      run: dotnet restore
#    - name: Build
#      run: dotnet build --configuration Release --no-restore

#    - name: Test
#      run: dotnet test --no-restore --verbosity normal
