name: .NET Core

on:
  push:
    branches: [ err/migrate-netstandard ]
  pull_request:
    branches: [ err/migrate-netstandard ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Set Variables and build
      run: |
        export DAY=$(date -d "$D" '+%-d')
        export MONTH=$(date -d "$D" '+%-m')
        export YEAR=$(date -d "$D" '+%y')
        export VERSION=1.$YEAR.$MONTH.$DAY$BITBUCKET_BUILD_NUMBER                
        dotnet build -p:Version=$VERSION --configuration Release -o /nuget      

#    - name: Install dependencies
#      run: dotnet restore
#    - name: Build
#      run: dotnet build --configuration Release --no-restore

#    - name: Test
#      run: dotnet test --no-restore --verbosity normal
